version: "3.0"

services:
  db:
    image: "postgres:latest"
    restart: always
    volumes:
      - "../data-base/postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"

  app:           # Nombre de la imagen
    image: "web:latest"
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:admin123@db/postgres
    depends_on:
      - db
    ports:
      - "127.0.0.1:9900:9900"       # El primer puerto es para ingresar desde el navegador, el segundo el puerto configurado en el .env